import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Axios from "axios";
import {useEffect, useState} from "react";


export default function Home() {

  const [pokeList, setPokeList] = useState([])
  const [pokeSearch, setPokeSearch] = useState([])

  fetch("https://pokeapi.co/api/v2/pokemon?limit=151")
      .then(response => response.json())
      .then(json => console.log(setPokeList(json.results)))

  const validateInput = (e)=>{
    e.preventDefault();

    setPokeSearch(e.target.pokename.value);

  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the React Pokedex made with <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          Get started by searching for a pokemon!
        </p>
        <div>
          <form onSubmit={validateInput}>
            <label>Pokemon Name:
              <input type="text" name='pokename' ></input>
            </label>
            <br/>
            <button type="submit">Save</button>
          </form>
        </div>
        <div className={styles.grid}>
          {pokeList.map(pokeList => <a href={pokeList.url} className={styles.card}>
            <h2>{pokeList.name}</h2>
            {/*<img src={pokeList.url.get(0).sprites.front_default} />*/}
            {/*<p>{pokeList.url.sprites}</p>*/}
          </a>)}
        </div>

        <div>
          <ul>
            {pokeList.map(pokeList => <li>{pokeList.name}</li>)}
          </ul>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
